### ISSUE TITLE
Execution failed for task ':app:processDebugGoogleServices'. 

### ISSUE THREAD

**Issue by Aadii-shah** [amruta-kashikar/CovidPatients#1]
File google-services.json is missing. The Google Services Plugin cannot function without it.

**Comment by amruta-kashikar** [comment]
After you clone this repository in your system you will have to  connect your firebase account with the app

**Comment by devu6776** [comment]
should i create my own project in firebase

**Comment by amruta-kashikar** [comment]
Yes

**Comment by devu6776** [comment]
Please guide me to create database of hospital list in firebase

**Comment by amruta-kashikar** [comment]
You will have to create a new account for hospitals as the list is auto-updated when a new hospital account is created. And one more thing add both apps in one firebase project
